### ISSUE TITLE
Some problems on the reproduction of papers

### ISSUE THREAD

**Issue by MeatballCat** [sane-lab/Trisk#1]
Hello, Mao, due to the need of research, I am trying to reproduce the results of your paper. I have some questions to ask you during the reproduction process.
1. Can you provide a copy of the relevant data set of stock, or tell us the general content structure of the data set?
2. In the process of reproducing micro-bench.sh, I found timer.output does not record any data. Would you please tell me which file the output data collection is in?
Looking forward to your reply, thank you.

**Comment by yancanmao** [comment]
Hi,

1. The stock data set is confidential and will not be open-sourced. The structure of each order in the stock app will be looked like this:
order_id|stock_id|trade_direction|price|timestamp

2. The output data will be maintained in the $EXP_DIR, there will be a set of "xx.output" files that record the latency rawdata of each task.
Here is some demo output you are supposed to have for a task named "Splitter FlatMap-9.output"
![image](https://user-images.githubusercontent.com/24371733/147072503-ab594ac1-0bba-4e8a-90ac-2c5201c57017.png)

**Comment by MeatballCat** [comment]
Hi,
Thank you for your reply. After receiving your data structure, I began to construct the stock dataset. After I constructed it according to your format, I found that the shell script still could not run normally. After I checked your code, I found that no data would be loaded in addsource.
![flink_addsource](https://user-images.githubusercontent.com/58537183/147196134-1f5595a7-c8c4-4ea8-ad64-dfedfb5c9c5a.png)
According to the structure you give, the length of the array obtained by the split function must be less than 8, so it will not execute the following collect function. The following is a piece of data I randomly generated. Does he have a problem?
![stock_data](https://user-images.githubusercontent.com/58537183/147196150-e1ed9ac5-425c-4c6e-8fdb-a34021b088f8.png)
Can you give me an example of an actual sample？

**Comment by yancanmao** [comment]
Hi,

In general, the source operator of the stock exchange will read through a hard-coded file path to generate the stock order stream.

The application cannot run normally because the dataset should be strictly consistent with the provided data format.

Here is a sample quote order in the stock exchange, we randomly put a value for each index:

```1234|A|20211223|09:30:00|0.4241197|20211223|09:30:00|0.4300000|12.45000|0.000|5677.000|756756|456456|A123456|A|45645|289283F231|12|O|L||N|S||N|```

And as we said, because the dataset is confidential, we could not explain the meaning of each index, it would be better to modify based on the provided code with a synthetic data generator for the stock exchange application.

You can find the source code of stock exchange application in `InAppStatefulStockExchange.java`.

**Comment by MeatballCat** [comment]
> Hi,
> 
> In general, the source operator of the stock exchange will read through a hard-coded file path to generate the stock order stream.
> 
> The application cannot run normally because the dataset should be strictly consistent with the provided data format.
> 
> Here is a sample quote order in the stock exchange, we randomly put a value for each index:
> 
> `1234|A|20211223|09:30:00|0.4241197|20211223|09:30:00|0.4300000|12.45000|0.000|5677.000|756756|456456|A123456|A|45645|289283F231|12|O|L||N|S||N|`
> 
> And as we said, because the dataset is confidential, we could not explain the meaning of each index, it would be better to modify based on the provided code with a synthetic data generator for the stock exchange application.
> 
> You can find the source code of stock exchange application in `InAppStatefulStockExchange.java`.

I see. Thank you for your reply！
